<?xml version="1.0"?>
<package format="2">
  <name>gimbal_yaw_bridge</name>
  <version>0.0.1</version>
  <description>Bridge auto-aim yaw angle (Float32) into JointState for TF (chassis->gimbal_yaw).</description>
  <maintainer email="bwyoung252006@gmail.com">Alphabet</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>gimbal_yaw_interfaces</depend>
  <depend>geometry_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>rmoss_interfaces</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
